Waveguide: Add convenience methods for 90° left and right turns
HelgeGehring/gdshelpers pull request #38
Opened 2020-12-02 15:13 UTC by fbeutel

I frequently need to perform left and right turns  and I think these methods would improve readability of the code

2020-12-02 15:52 UTC, frank-bp requested changes
Nice idea, but a "flexible" angle would be nice for directional couplers and similar structures.

2020-12-02 15:52 UTC, frank-bp commented on gdshelpers/parts/waveguide.py
> +        return self.add_bend(0.5*np.pi, bend_radius)
`
```suggestion
    def add_left_bend(self, radius, angle=np.pi/2):
        """
        Add a left turn (90° or as defined by angle) with the given bend radius
        """
        return self.add_bend(angle, radius)
```

2020-12-02 15:52 UTC, frank-bp commented on gdshelpers/parts/waveguide.py
> +        return self.add_bend(-0.5*np.pi, bend_radius)
```suggestion

    def add_right_bend(self, radius, angle=np.pi/2):
        """
        Add a right turn (90° or as defined by angle) with the given bend radius
        """
        return self.add_bend(-angle, radius)
```

2020-12-03 18:19 UTC, HelgeGehring commented
Looks good, thanks!

2020-12-03 18:19 UTC, merged